# Formation energy prediction

> Requires the dev installation (see README): `uv pip install -e ".[dev]"`

The input to the model can be CIF files, POSCAR (use `input_format='vasp'`), PyMatGen Structures or ASE Atoms.

- **Example 1:** passing the CIF files directly to the model and getting the predictions.
- **Example 2:** creating the image generator first, to check which crystals are valid for the model and to get the predictions of all rotational ensembles.

In [1]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)  # pandas deprecation warnings

from xiespp import formation_energy, get_test_samples

model = formation_energy.FormationEnergyPredictor()  # device='/device:GPU:0' to use a GPU
model

## Example 1: CIF files → formation energy

In [2]:
cif_files = sorted(get_test_samples('MoS2'))
cif_files

['/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_12.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_136.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_14.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_141.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_194.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_33.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_61.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_62.cif',
 '/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_74.cif']

In [3]:
# Formation energy (eV/atom) of each input file (NaN for crystals that do not meet the requirements of the model)
yp = model.predict(cif_files, verbose=0)
yp

0   -1.050841
1   -1.060828
2   -0.975813
3   -1.062675
4   -0.401412
5   -0.897200
6   -0.825773
7   -0.798746
8   -0.518448
Name: mean, dtype: float64

## Example 2: Using the image generator
The image generator reads the structures and prepares the CVR images once; it can then be passed to the model.

In [4]:
gen = formation_energy.prepare_data(
    data_input=cif_files,
    # input_format='vasp',  # Use this if the files are not CIF files
)

Reading CIF files...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 185.85it/s]

Preparing image objects...

Checking image requirements...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 6319.90it/s]

Valid images:       9 /       9

Preparing point clouds...

  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:00<00:00, 3178.57it/s]

In [5]:
# Crystals that do not meet the requirements of the model are marked as not valid
gen.df[['file', 'is_valid']]

                                                file  is_valid
0  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
1  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
2  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
3  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
4  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
5  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
6  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
7  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True
8  /opt/gpudata/davari/XIE-SPP/xiespp/synthesizab...      True

In [6]:
yp = model.predict(gen, return_all_ensembles=True, verbose=0)

# Besides the final prediction (mean, eV/atom), the values of all the rotational ensembles are reported.
# Missing values are the crystals that did not meet the requirements of the model.
# If return_all_ensembles is False, only the mean value is returned.
yp

,mean,0,1,2,3,4,5,6,7,8,...,40,41,42,43,44,45,46,47,48,49
0,-1.060106,-0.970626,-1.222099,-1.079518,-1.011548,-1.090279,-0.965212,-1.015526,-1.048818,-1.136680,...,-1.037327,-1.021059,-1.032096,-1.056803,-1.142456,-1.097623,-1.091528,-0.999465,-1.002254,-1.070674
1,-1.058043,-1.070561,-1.093590,-0.923165,-1.064950,-1.272597,-1.150170,-1.058558,-0.919890,-1.059034,...,-1.066842,-1.128700,-1.030791,-1.036693,-1.038370,-1.134693,-1.076874,-1.166290,-1.060038,-0.999762
2,-0.951065,-0.959354,-0.850909,-1.005397,-1.000163,-0.814666,-1.036457,-0.869359,-0.981459,-0.779763,...,-0.967826,-0.956513,-0.962858,-0.922761,-0.959093,-0.937898,-0.902006,-0.941057,-0.932135,-0.957371
3,-1.084398,-0.981843,-1.072466,-0.945671,-0.970604,-1.104405,-1.214927,-1.132539,-0.935310,-1.114663,...,-1.035263,-1.045171,-1.089934,-0.997855,-1.143891,-1.069381,-1.082913,-1.016939,-1.113882,-1.208815
4,-0.406677,-0.349330,-0.369886,-0.388413,-0.497318,-0.459787,-0.431128,-0.395959,-0.441699,-0.315877,...,-0.457192,-0.382773,-0.363962,-0.285400,-0.494094,-0.439809,-0.467141,-0.429428,-0.410798,-0.457987
5,-0.918732,-0.869851,-0.922136,-0.929494,-0.974652,-0.952712,-0.936805,-0.952885,-0.878210,-0.909485,...,-0.852131,-0.931781,-0.795381,-0.883794,-0.941978,-1.035080,-0.865848,-0.912431,-0.909784,-0.939126
6,-0.857725,-0.938650,-0.853382,-0.915635,-0.783165,-0.769029,-0.893135,-0.786645,-0.916327,-0.952767,...,-0.745511,-0.776260,-0.803467,-0.811910,-0.886180,-0.903229,-0.860458,-0.747327,-0.960439,-0.905298
7,-0.798716,-0.809555,-0.700380,-0.855542,-0.996273,-0.891135,-0.824450,-0.775468,-0.776375,-0.692122,...,-0.760956,-0.814249,-0.753402,-0.786483,-0.827706,-0.856587,-0.757398,-0.830079,-0.800217,-0.856291
8,-0.529402,-0.487543,-0.528711,-0.568424,-0.507923,-0.505061,-0.492978,-0.421929,-0.559213,-0.508393,...,-0.504686,-0.585621,-0.459150,-0.597714,-0.473054,-0.595349,-0.492204,-0.524235,-0.472340,-0.698088

### (Optional) Structures from the Materials Project
PyMatGen structures can be used in the same way. Set the `MP_API_KEY` environment variable (or paste your key below) to run this cell.

In [7]:
import os

api_key = os.environ.get('MP_API_KEY')  # or: api_key = '__YOUR_API_KEY__'
if api_key:
    from mp_api.client import MPRester
    with MPRester(api_key) as mpr:
        docs = mpr.materials.summary.search(chemsys='Si-O', fields=['material_id', 'structure'])[:10]
    yp_mp = model.predict([d.structure for d in docs], verbose=0)
    yp_mp.index = [d.material_id for d in docs]
    display(yp_mp)
else:
    print('MP_API_KEY is not set: skipped.')

MP_API_KEY is not set: skipped.

## Command line usage
Run `xiespp formation-energy -h` for all options.

In [8]:
!xiespp formation-energy --test-samples MoS2 -o formation_energy.csv 2>/dev/null

file,formation_energy
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_12.cif,-1.0709485018253326
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_136.cif,-1.085028270483017
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_14.cif,-0.9802907264232635
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_141.cif,-1.0823233151435852
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_194.cif,-0.4157546424865723
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_33.cif,-0.9044769191741944
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_61.cif,-0.8374607455730438
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_62.cif,-0.7969144296646118
/opt/gpudata/davari/XIE-SPP/xiespp/synthesizability_1/data/MoS2/MoS2_74.cif,-0.5218638968467713